# Generated by Django 6.1.1 on 2026-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('endereco', models.CharField(max_length=256)),
                ('data_de_nascimento', models.CharField(max_length=256)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('motorista', models.ManyToManyField(blank=True, to='entregas.motorista')),
            ],
        ),
    ]
