# Generated by Django 6.1.1 on 2026-09-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='endereco',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=50, unique=True)),
                ('destino', models.TextField()),
                ('status', models.CharField(blank=True, max_length=1)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.motorista')),
            ],
        ),
    ]
