# Generated by Django 6.1.1 on 2026-09-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_alter_motorista_endereco_pacote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caminhao',
            options={'verbose_name': 'Caminhão', 'verbose_name_plural': 'Caminhões'},
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='placa',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entregas.motorista', verbose_name='Motorista Responsável'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('T', 'Em Trânsito'), ('E', 'Entregue'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
    ]
