# Generated by Django 6.1.1 on 2026-09-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_alter_caminhao_options_alter_caminhao_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='data_de_nascimento',
            new_name='data_nascimento',
        ),
    ]
