# Generated by Django 6.1.1 on 2026-09-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_rename_data_de_nascimento_motorista_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
