# Generated by Django 6.1.1 on 2026-09-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_motorista_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='cliente',
            field=models.CharField(max_length=150, null=True, verbose_name='Destinatario'),
        ),
    ]
