# Generated by Django 6.1.1 on 2026-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0006_pacote_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='telefone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
