# Generated by Django 6.1.1 on 2026-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0007_pacote_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='telefone',
            field=models.CharField(max_length=14, null=True, verbose_name='Telefone do Cliente'),
        ),
    ]
